# github.com/pahasara/HyprDots

[manager]
cwd = { fg = "#33ccff" }

# Hovered
hovered         = { fg = "#1e1e2e", bg = "#4caef0" }
preview_hovered = { underline = false }

# Find
find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_selected = { fg = "#4caef0", bg = "#89b4fa" }

# Tab
tab_active   = { fg = "#1e1e2e", bg = "#2cb6fe" }
tab_inactive = { fg = "#2cb6fe", bg = "#000000" }
tab_width    = 1

# Count
count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#4caef0" }

# Border
border_symbol = "│"
border_style  = { fg = "#6f748c" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#000000", bg = "#000000" }

# Mode
mode_normal = { fg = "#1e1e2e", bg = "#4caef0", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#4caef0", bg = "#000000" }
progress_error  = { fg = "#f38ba8", bg = "#000000" }

# Permissions
permissions_t = { fg = "#4caef0" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#7f849c" }

[input]
border   = { fg = "#4caef0" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#4caef0" }
active   = { fg = "#f5c2e7" }
inactive = {}

[tasks]
border  = { fg = "#4caef0" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#33ccff" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }

[help]
on      = { fg = "#f5c2e7" }
exec    = { fg = "#33ccff" }
desc    = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer  = { fg = "#000000", bg = "#2cb6fe" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#33ccff" },

	# Videos
	{ mime = "video/*", fg = "#f9e2af" },
	{ mime = "audio/*", fg = "#f9e2af" },

	# Archives
	{ mime = "application/zip",             fg = "#f5c2e7" },
	{ mime = "application/gzip",            fg = "#f5c2e7" },
	{ mime = "application/x-tar",           fg = "#f5c2e7" },
	{ mime = "application/x-bzip",          fg = "#f5c2e7" },
	{ mime = "application/x-bzip2",         fg = "#f5c2e7" },
	{ mime = "application/x-7z-compressed", fg = "#f5c2e7" },
	{ mime = "application/x-rar",           fg = "#f5c2e7" },

	# Fallback
	{ name = "*", fg = "#2cb6fe" },
	{ name = "*/", fg = "#4caef0" }
]
