# github.com/pahasara/HyprDots

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 3, 3 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "size" # u can use 'size_and_mtime' here
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 4
max_width       = 1200
max_height      = 1200
cache_dir       = "~/.cache/yazi/"
image_delay     = 1
image_filter    = "lanczos3"
image_quality   = 90
ueberzug_scale  = 1.0
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
{ run = '${EDITOR:-vi} "%*"', block = true, desc = "$EDITOR", for = "unix" },
{ run = 'code "%*"', orphan = true, desc = "code", for = "windows" },
{ run = 'code -w "%*"', block = true, desc = "code (block)", for = "windows" },
]

open = [
{ run = 'xdg-open "%1"', desc = "Open", for = "linux" },
{ run = 'open "%@"', desc = "Open", for = "macos" },
{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
{ run = 'termux-open "%1"', desc = "Open", for = "android" },
]

view = [
{ run = 'imv "%1"', orphan = true, for = "linux" },
]

play = [
{ run = 'mpv --force-window "%*"', orphan = true, for = "unix" },
{ run = 'mpv --force-window "%*"', orphan = true, for = "windows" },
{ run = 'mediainfo "%1"; echo "Press enter to exit"; read _', block = true, desc = "Show media info", for = "unix" },
]

extract = [
{ run = 'ya pub extract --list "%*"', desc = "Extract here" },
]

[open]
rules = [
{ url = "*/", use = [ "edit", "open", "reveal" ] },
{ mime = "text/*", use = [ "edit", "reveal" ] },
{ mime = "image/*", use = [ "view", "reveal" ] },
{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
{ mime = "inode/empty", use = [ "edit", "reveal" ] },
{ url = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers = 10
macro_workers = 10
bizarre_retry = 3
image_alloc   = 1073741824
image_bound   = [ 0, 0 ]

[plugin]
prepend_preloaders = [
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
    { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
    { mime = "application/postscript", run = "mediainfo" },
]

fetchers = [
{ id = "mime", url = "*/",         run = "mime.dir",   prio = "high" },
{ id = "mime", url = "local://*",  run = "mime.local", prio = "high" },
{ id = "mime", url = "remote://*", run = "mime.remote", prio = "high" },
]

spotters = [
{ url = "*/", run = "folder" },
{ mime = "text/*", run = "code" },
{ mime = "image/*", run = "image" },
{ mime = "video/*", run = "video" },
{ url = "*", run = "file" },
]

preloaders = [
{ mime = "image/*", run = "image" },
{ mime = "video/*", run = "video" },
{ mime = "application/pdf", run = "pdf" },
]

previewers = [
{ url = "*/", run = "folder" },
{ mime = "text/*", run = "code" },
{ mime = "application/{json,ndjson}", run = "json" },
{ mime = "image/*", run = "image" },
{ mime = "video/*", run = "video" },
{ mime = "application/pdf", run = "pdf" },
{ mime = "inode/empty", run = "empty" },
{ url = "*", run = "file" },
]

[input]
cursor_blink = false
